# Generated by Django 3.2.5 on 2021-08-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_auto_20210816_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='horario_autorizacao',
            new_name='horario_autorização',
        ),
    ]
